trigger:
- master

pool:
  vmImage: windows-latest

variables:
  phpVersion: 8.1

steps:
- script: |
    php -v
  displayName: 'Verify PHP version'
- task: BlazeMeter Integration@2
  inputs:
    selectTask: 'createPerformaceTest'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    reportName: 'UploadedJMX'
    selectuploadforPerformanceTest: 'uploadfile'
    updateMainTestFile: true
    inputstartfile: 'login_test.jmx'
    testname: 'pipeline-test'
    totalusers: 0
    duration: 0
    rampup: 0
    showtaillog: true

- task: BlazeMeter Integration@2
  condition: false  # This disables the task
  inputs:
    selectTask: 'createPerformaceTest'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    reportName: 'Sample'
    testname: 'sample'
- task: BlazeMeter Integration@2
  displayName: "BlazeMeter Test"
  condition: false  # This disables the task
  inputs:
    selectTask: 'runExistingTest'
    testurl: 'https://a.blazemeter.com/app/#/accounts/$(AccountID)/workspaces/$(WorkSpaceID)/projects/2066897/tests/14780821/edit'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    selectUploadfile: 'No'
    showtaillog: true
