trigger:
- master

pool:
  vmImage: windows-latest

variables:
  phpVersion: 8.1

steps:
- script: |
    php -v
  displayName: 'Verify PHP version'

- task: Blaze-Runner.Blaze-Runner.Blazemeter-Test.BlazeMeter Integration@2
  displayName: 'BlazeMeter Integration'
  condition: false  # This disables the task
  inputs:
    selectTask: createPerformaceTest
    reportName: MyTest
    updateMainTestFile: true
    inputstartfile: 'dbank-login.jmx'
    testname: testname
    buildStatus: false
- task: BlazeMeter Integration@2
  condition: true  # This disables the task
  inputs:
    selectTask: 'createPerformaceTest'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    reportName: 'UploadedJMX'
    selectuploadforPerformanceTest: 'uploadfile'
    updateMainTestFile: true
    inputstartfile: 'dbank-login.jmx'
    testname: 'pipeline-test-5-jmx'
    totalusers: 0
    duration: 0
    rampup: 0
    showtaillog: true

- task: BlazeMeter Integration@2
  condition: false  # This disables the task
  inputs:
    selectTask: 'createPerformaceTest'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    reportName: 'Sample'
    testname: 'sample'
    updateMainTestFile: true
    inputstartfile: 'dbank-login.jmx'
- task: BlazeMeter Integration@2
  displayName: "BlazeMeter Test"
  condition: false  # This disables the task
  inputs:
    selectTask: 'runExistingTest'
    testurl: 'https://a.blazemeter.com/app/#/accounts/$(AccountID)/workspaces/$(WorkSpaceID)/projects/2066897/tests/14780821/edit'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    selectUploadfile: 'No'
    showtaillog: true
