trigger:
- master

pool:
  vmImage: windows-latest

variables:
  phpVersion: 8.1

steps:
- script: |
    php -v
  displayName: 'Verify PHP version'
- task: PowerShell@2
  name: ReadParams
  inputs:
    targetType: 'inline'
    script: |
      $paramsFile = "$(Build.SourcesDirectory)\blz_load_config.json"
      Write-Host "Reading params from $paramsFile"

      $params = Get-Content $paramsFile | ConvertFrom-Json

      Write-Host "Loaded values:"
      Write-Host "VUsers = $($params.VUsers)"
      Write-Host "TestDuration = $($params.TestDuration)"
      Write-Host "RampUpTime = $($params.RampUpTime)"

      Write-Host "##vso[task.setvariable variable=VUsers]$($params.VUsers)"
      Write-Host "##vso[task.setvariable variable=TestDuration]$($params.TestDuration)"
      Write-Host "##vso[task.setvariable variable=RampUpTime]$($params.RampUpTime)"
- script: |
    echo "Users: $(VUsers)"
    echo "Duration: $(TestDuration)"
    echo "Ramp: $(RampUpTime)"
  displayName: 'Use test parameters'

- task: Blaze-Runner.Blaze-Runner.Blazemeter-Test.BlazeMeter Integration@2
  displayName: 'BlazeMeter Integration'
  condition: false  # This disables the task
  inputs:
    selectTask: createPerformaceTest
    reportName: MyTest
    updateMainTestFile: true
    inputstartfile: 'dbank-login.jmx'
    testname: testname
    buildStatus: false
- task: BlazeMeter Integration@2
  condition: false  # This enables  the task
  inputs:
    selectTask: 'createPerformaceTest'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    reportName: 'Azure Release $(Build.BuildId)'
    selectuploadforPerformanceTest: 'uploadfile'
    updateMainTestFile: true
    inputstartfile: 'dbank-login.jmx'
    testname: 'pipeline-test-jmx'
    totalusers: '$(VUsers)'
    duration: '$(TestDuration)'
    rampup: $(RampUpTime)
    showtaillog: true
    buildStatus: false
    projectID: 2066897

- task: BlazeMeter Integration@2
  condition: false  # This enables  the task
  inputs:
    selectTask: 'runExistingTest'
    testurl: 'https://a.blazemeter.com/app/#/accounts/352831/workspaces/1787337/projects/2066897/tests/14772546/edit'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    reportName: 'runtest'
    selectUploadfile: 'No'
    showtaillog: true
    totalusers: '$(VUsers)'
    duration: '$(TestDuration)'
    rampup: $(RampUpTime)
    buildStatus: false

- task: BlazeMeter Integration@2
  condition: false  # This enables  the task
  inputs:
    selectTask: 'createPerformaceTest'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    reportName: 'UploadedJMX'
    selectuploadforPerformanceTest: 'uploadfile'
    updateMainTestFile: true
    inputstartfile: 'dbank-login.jmx'
    testname: 'pipeline-test-5-jmx'
    showtaillog: true
    buildStatus: false

- task: BlazeMeter Integration@2
  condition: false  # This disables the task
  inputs:
    selectTask: 'createPerformaceTest'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    reportName: 'Sample'
    testname: 'sample'
    updateMainTestFile: true
    inputstartfile: 'dbank-login.jmx'
- task: BlazeMeter Integration@2
  displayName: "BlazeMeter Test"
  condition: true  # This disables the task
  inputs:
    selectTask: 'runExistingTest'
    testurl: 'https://a.blazemeter.com/app/#/accounts/$(AccountID)/workspaces/$(WorkSpaceID)/projects/2066897/tests/14780821/edit'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    selectUploadfile: 'No'
    buildStatus: false
