trigger:
- master

pool:
  vmImage: windows-latest

variables:
  phpVersion: 8.1

steps:
- script: |
    php -v
  displayName: 'Verify PHP version'

- task: BlazeMeter Integration@2
  condition: false  # This enables  the task
  inputs:
    selectTask: 'createPerformaceTest'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    reportName: 'Azure Release $(Build.BuildId)'
    selectuploadforPerformanceTest: 'uploadfile'
    updateMainTestFile: true
    inputstartfile: 'dbank-login.jmx'
    testname: 'pipeline-test-jmx'
    totalusers: '$(VUsers)'
    duration: '$(TestDuration)'
    rampup: $(RampUpTime)
    showtaillog: true
    buildStatus: false
    projectID: 2066897


- task: BlazeMeter Integration@2
  displayName: "BlazeMeter Load Test"
  condition: true  # This disables the task
  inputs:
    selectTask: 'runExistingTest'
    testurl: 'https://a.blazemeter.com/app/#/accounts/$(AccountID)/workspaces/$(WorkSpaceID)/projects/2066897/tests/14780821/edit'
    apikey: '$(APIKEY)'
    apisecret: '$(APISECRET)'
    reportName: 'Azure Release $(Build.BuildId)'
    selectUploadfile: 'Yes'
    totalusers: '$(VUsers)'
    duration: '$(Perf_Duration)'
    rampup: '$(RampUpTime)'
    concurrencyControlEnabled: true
    buildStatus: false
    updateMainTestFile: true
    inputstartfile: 'dbank-login.jmx'